---
- hosts: all
  remote_user: root
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes
        cache_valid_time: 86400
        autoclean: yes
        upgrade: dist
        force_apt_get: yes
